//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSumaCSharp.Servicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicio/", ConfigurationName="Servicio.wsAritmeticaJava")]
    public interface wsAritmeticaJava {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://Servicio/).
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/wsAritmeticaJava/sumarRequest", ReplyAction="http://Servicio/wsAritmeticaJava/sumarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSumaCSharp.Servicio.sumarResponse sumar(ClienteSumaCSharp.Servicio.sumarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/wsAritmeticaJava/sumarRequest", ReplyAction="http://Servicio/wsAritmeticaJava/sumarResponse")]
        System.Threading.Tasks.Task<ClienteSumaCSharp.Servicio.sumarResponse> sumarAsync(ClienteSumaCSharp.Servicio.sumarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumar", WrapperNamespace="http://Servicio/", IsWrapped=true)]
    public partial class sumarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int b;
        
        public sumarRequest() {
        }
        
        public sumarRequest(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumarResponse", WrapperNamespace="http://Servicio/", IsWrapped=true)]
    public partial class sumarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public sumarResponse() {
        }
        
        public sumarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsAritmeticaJavaChannel : ClienteSumaCSharp.Servicio.wsAritmeticaJava, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsAritmeticaJavaClient : System.ServiceModel.ClientBase<ClienteSumaCSharp.Servicio.wsAritmeticaJava>, ClienteSumaCSharp.Servicio.wsAritmeticaJava {
        
        public wsAritmeticaJavaClient() {
        }
        
        public wsAritmeticaJavaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsAritmeticaJavaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAritmeticaJavaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAritmeticaJavaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSumaCSharp.Servicio.sumarResponse ClienteSumaCSharp.Servicio.wsAritmeticaJava.sumar(ClienteSumaCSharp.Servicio.sumarRequest request) {
            return base.Channel.sumar(request);
        }
        
        public int sumar(int a, int b) {
            ClienteSumaCSharp.Servicio.sumarRequest inValue = new ClienteSumaCSharp.Servicio.sumarRequest();
            inValue.a = a;
            inValue.b = b;
            ClienteSumaCSharp.Servicio.sumarResponse retVal = ((ClienteSumaCSharp.Servicio.wsAritmeticaJava)(this)).sumar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSumaCSharp.Servicio.sumarResponse> ClienteSumaCSharp.Servicio.wsAritmeticaJava.sumarAsync(ClienteSumaCSharp.Servicio.sumarRequest request) {
            return base.Channel.sumarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSumaCSharp.Servicio.sumarResponse> sumarAsync(int a, int b) {
            ClienteSumaCSharp.Servicio.sumarRequest inValue = new ClienteSumaCSharp.Servicio.sumarRequest();
            inValue.a = a;
            inValue.b = b;
            return ((ClienteSumaCSharp.Servicio.wsAritmeticaJava)(this)).sumarAsync(inValue);
        }
    }
}
